name: Run Selenium Script

on:
  schedule:
    - cron: '0 8 * * 1'  # 毎週月曜日の午前8時に実行

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ChromeDriver and Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium script
        run: |
          python script.py
